spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/mmo
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    data: src/main/resources/data.sql
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop