INSERT INTO accounts (nick_name, password)
VALUES
    ('DragonSlayer77', 'password1'),
    ('TheWizard42', 'password2'),
    ('ShadowNinja', 'password3'),
    ('BlazeFire', 'password4'),
    ('IceQueen123', 'password5'),
    ('Thunderbolt56', 'password6'),
    ('ChaosKnight', 'password7'),
    ('MysticPhoenix', 'password8'),
    ('CrystalMage', 'password9'),
    ('SteelWarrior', 'password10'),
    ('SwiftArrow', 'password11'),
    ('MoonlightAssassin', 'password12'),
    ('FlameWarlock', 'password13'),
    ('Frostbite', 'password14'),
    ('TheVengefulOne', 'password15'),
    ('SoulEater666', 'password16'),
    ('DragonHeart', 'password17'),
    ('TheSilentBlade', 'password18'),
    ('TheLastSamurai', 'password19'),
    ('PhoenixRider', 'password20');

INSERT INTO characters (account_id, name, c_level, job, gender)
VALUES
(1, 'Gryffindor', 1, 'Mage', 'm'),
(1, 'Lunara', 1, 'Warrior', 'f'),
(4, 'Thorn', 1, 'Tank', 'm'),
(4, 'Kiera', 1, 'Mage', 'f'),
(5, 'Drax', 1, 'Warrior', 'm'),
(6, 'Nyx', 1, 'Tank', 'f'),
(17, 'Drogath', 1, 'Mage', 'm'),
(8, 'Sarina', 1, 'Warrior', 'f'),
(9, 'Axl', 1, 'Tank', 'm'),
(10, 'Lilith', 1, 'Mage', 'f'),
(16, 'Grommash', 1, 'Warrior', 'm'),
(12, 'Nimue', 1, 'Tank', 'f'),
(13, 'Morgath', 1, 'Mage', 'm'),
(14, 'Aria', 1, 'Warrior', 'f'),
(3, 'Lucien', 1, 'Tank', 'm'),
(6, 'Eira', 1, 'Mage', 'f'),
(17, 'Balthazar', 1, 'Warrior', 'm'),
(5, 'Raine', 1, 'Tank', 'f'),
(19, 'Ozzy', 1, 'Mage', 'm'),
(20, 'Raven', 1, 'Warrior', 'f');