INSERT INTO accounts (nick_name, password)
VALUES
    ('DragonSlayer77', 'password1'),
    ('TheWizard42', 'password2'),
    ('ShadowNinja', 'password3'),
    ('BlazeFire', 'password4'),
    ('IceQueen123', 'password5'),
    ('Thunderbolt56', 'password6'),
    ('ChaosKnight', 'password7'),
    ('MysticPhoenix', 'password8'),
    ('CrystalMage', 'password9'),
    ('SteelWarrior', 'password10'),
    ('SwiftArrow', 'password11'),
    ('MoonlightAssassin', 'password12'),
    ('FlameWarlock', 'password13'),
    ('Frostbite', 'password14'),
    ('TheVengefulOne', 'password15'),
    ('SoulEater666', 'password16'),
    ('DragonHeart', 'password17'),
    ('TheSilentBlade', 'password18'),
    ('TheLastSamurai', 'password19'),
    ('PhoenixRider', 'password20');